spring:
  datasource:
    url: postgresql://postgres:tBxMMSCzCXgucLOiScvCIwLkZvydfulT@switchyard.proxy.rlwy.net:39768/railway
    username: postgres
    password: tBxMMSCzCXgucLOiScvCIwLkZvydfulT
  jpa:
    hibernate:
      ddl-auto: validate
server:
  port: ${PORT:8080}